Repository AY2223S2-CS2113-T15-1/tp, pull requests merged in 2023-04, with the labels that each got.

#203 Fix: address all problems from PE-D
  docs/UserGuide.md
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/AddCodeCommand.java
  src/main/java/seedu/clialgo/command/AddNoteCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/main/java/seedu/clialgo/storage/FileEncoder.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/main/java/seedu/clialgo/storage/SingleFile.java
Labels: type.Bug, priority.High, severity.High

#204 Add Ui to DG
  docs/DeveloperGuide.md
  docs/sequence-diagrams/diagrams/Ui.png
  docs/sequence-diagrams/source-files/HelpFeature.puml
  docs/sequence-diagrams/source-files/Ui.puml
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/FilterCommand.java
  src/test/java/seedu/clialgo/UiTest.java
  src/test/java/seedu/clialgo/command/FilterCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#208 Update PPP v2.1
  docs/DeveloperGuide.md
  docs/sequence-diagrams/diagrams/Ui.png
  docs/sequence-diagrams/source-files/Ui.puml
  docs/team/ongheejet.md
Labels: type.Task, priority.High

#210 Add table of contents and update UserGuide v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/sequence-diagrams/diagrams/TopoSort.png
  docs/sequence-diagrams/source-files/TopoSort.puml
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/test/java/seedu/clialgo/UiTest.java
Labels: type.Task, priority.High

#209 Update importance feature for CS2040CFile, Specify Case sensitivity and Documents accepted in UG
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#217 Fix: removed footbox
  docs/sequence-diagrams/diagrams/AddEntry.png
  docs/sequence-diagrams/diagrams/Export.png
  docs/sequence-diagrams/diagrams/InitializationFileManager.png
  docs/sequence-diagrams/source-files/AddEntry.puml
  docs/sequence-diagrams/source-files/Export.puml
  docs/sequence-diagrams/source-files/InitializationFileManager.puml
Labels: priority.Low

#226 Refactor code v2.1
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/sequence-diagrams/diagrams/AddFeature.png
  docs/sequence-diagrams/diagrams/Architecture.png
  docs/sequence-diagrams/diagrams/FilterByTopic.png
  docs/sequence-diagrams/diagrams/HelpFeature.png
  docs/sequence-diagrams/diagrams/InitializationFileManager.png
  docs/sequence-diagrams/diagrams/ListFeature.png
  docs/sequence-diagrams/diagrams/Parser.png
  docs/sequence-diagrams/diagrams/TopoSort.png
  docs/sequence-diagrams/source-files/AddFeature.puml
  docs/sequence-diagrams/source-files/Architecture.puml
  docs/sequence-diagrams/source-files/FilterByTopic.puml
  docs/sequence-diagrams/source-files/HelpFeature.puml
  docs/sequence-diagrams/source-files/InitializationFileManager.puml
  docs/sequence-diagrams/source-files/ListFeature.puml
  docs/sequence-diagrams/source-files/Parser.puml
  docs/sequence-diagrams/source-files/TopoSort.puml
  docs/team/heejet.md
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
Labels: type.Task, priority.High

#224 Add design and implementation for remove and update add sequence diagram
  docs/DeveloperGuide.md
  docs/class-diagrams/diagrams/RemoveClass.png
  docs/class-diagrams/source-files/RemoveClass.puml
  docs/sequence-diagrams/diagrams/AddFeature.png
  docs/sequence-diagrams/diagrams/RemoveFeature.png
  docs/sequence-diagrams/source-files/AddFeature.puml
  docs/sequence-diagrams/source-files/RemoveFeature.puml
  src/main/java/seedu/clialgo/TopicManager.java
Labels: type.Task, priority.High

#225 Add breaks for exceptions to match Step 2 of Ui in DG
  docs/DeveloperGuide.md
  docs/sequence-diagrams/diagrams/HelpFeature.png
  docs/sequence-diagrams/diagrams/Ui.png
  docs/sequence-diagrams/source-files/HelpFeature.puml
  docs/sequence-diagrams/source-files/Ui.puml
Labels: type.Task, priority.Medium

#228 Branch code review fix v2.1
  docs/sequence-diagrams/diagrams/Ui.png
  docs/sequence-diagrams/source-files/Ui.puml
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
Labels: type.Task, priority.High

#232 Add JUnit for TopoCommand v2.1
  Queue.txt
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/test/java/seedu/clialgo/command/TopoCommandTest.java
Labels: type.Task, priority.High

#234 Update PPP issue #155
  docs/team/heejet.md
  docs/team/nikhil.md
  docs/team/nikkiDEEE.md
Labels: type.Task, priority.High

#230 Updated JUnit tests
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/file/CS2040CFile.java
  src/main/java/seedu/clialgo/file/Code.java
  src/main/java/seedu/clialgo/file/Note.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/main/java/seedu/clialgo/storage/SingleFile.java
  src/test/java/seedu/clialgo/BufferTest.java
  src/test/java/seedu/clialgo/command/ExitTestModeCommandTest.java
  src/test/java/seedu/clialgo/storage/FileDecoderTest.java
  src/test/java/seedu/clialgo/storage/FileManagerTest.java
  src/test/java/seedu/clialgo/storage/SingleFileTest.java
Labels: type.Task, priority.Medium

#237 Update DG v2.1
  docs/DeveloperGuide.md
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
Labels: type.Task, priority.High

#238 Cleaned up "magic" string
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/storage/FileDecoder.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/test/java/seedu/clialgo/BufferTest.java
  src/test/java/seedu/clialgo/command/ExitTestModeCommandTest.java
  src/test/java/seedu/clialgo/command/FilterCommandTest.java
  src/test/java/seedu/clialgo/storage/FileDecoderTest.java
  src/test/java/seedu/clialgo/storage/FileManagerTest.java
  src/test/java/seedu/clialgo/storage/SingleFileTest.java
Labels: type.Task, priority.Medium

#241 Update Class Diagrams
  docs/class-diagrams/diagrams/ExportClass.png
  docs/class-diagrams/diagrams/FileManagerClass.png
  docs/class-diagrams/source-files/ExportClass.puml
  docs/class-diagrams/source-files/FileManagerClass.puml
Labels: type.Bug, priority.Medium

#242 Add PPP v2.1
  docs/DeveloperGuide.md
  docs/team/ong-ck.md
  docs/team/ongchuankai.md
Labels: type.Task, priority.Medium

#233 Add Junit test to AddCodeCommand, Address code review, Add PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/nicholas.md
  docs/team/nicholas132000.md
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/command/AddCodeCommand.java
  src/main/java/seedu/clialgo/command/AddNoteCommand.java
  src/test/java/seedu/clialgo/command/AddCodeCommandTest.java
  src/test/java/seedu/clialgo/command/AddNoteCommandTest.java
Labels: type.Task, priority.High

#244 Logic documentation v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/class-diagrams/diagrams/ArchitectureDiagram.png
  docs/class-diagrams/diagrams/ParserClass.png
  docs/class-diagrams/diagrams/TopicManagerClass.png
  docs/class-diagrams/source-files/ArchitectureDiagram.puml
  docs/class-diagrams/source-files/ParserClass.puml
  docs/class-diagrams/source-files/TopicManagerClass.puml
  docs/sequence-diagrams/diagrams/Architecture.png
  docs/sequence-diagrams/diagrams/TopicManager.png
  docs/sequence-diagrams/source-files/Architecture.puml
  docs/sequence-diagrams/source-files/TopicManager.puml
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/CLIAlgo.java
  src/main/java/seedu/clialgo/Parser.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/AddCodeCommand.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/AddNoteCommand.java
  src/main/java/seedu/clialgo/command/Command.java
  src/main/java/seedu/clialgo/command/EmptyBufferCommand.java
  src/main/java/seedu/clialgo/command/ExitCommand.java
  src/main/java/seedu/clialgo/command/ExitTestModeCommand.java
  src/main/java/seedu/clialgo/command/ExportCommand.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/FilterCommand.java
  src/main/java/seedu/clialgo/command/HelpCommand.java
  src/main/java/seedu/clialgo/command/InvalidCommand.java
  src/main/java/seedu/clialgo/command/InvalidFilterCommand.java
  src/main/java/seedu/clialgo/command/InvalidImportanceCommand.java
  src/main/java/seedu/clialgo/command/InvalidTopicCommand.java
  src/main/java/seedu/clialgo/command/ListCommand.java
  src/main/java/seedu/clialgo/command/NameNotFoundCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/main/java/seedu/clialgo/command/TestModeCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/main/java/seedu/clialgo/logic/Topic.java
  src/main/java/seedu/clialgo/logic/TopicManager.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/main/java/seedu/clialgo/storage/SingleFile.java
  src/test/java/seedu/clialgo/ParserTest.java
  src/test/java/seedu/clialgo/command/AddCodeCommandTest.java
  src/test/java/seedu/clialgo/command/AddCommandTest.java
  src/test/java/seedu/clialgo/command/AddNoteCommandTest.java
  src/test/java/seedu/clialgo/command/ExitTestModeCommandTest.java
  src/test/java/seedu/clialgo/command/FilterCommandTest.java
  src/test/java/seedu/clialgo/command/HelpCommandTest.java
  src/test/java/seedu/clialgo/command/InvalidTopicCommandTest.java
  src/test/java/seedu/clialgo/command/ListCommandTest.java
  src/test/java/seedu/clialgo/command/NameNotFoundCommandTest.java
  src/test/java/seedu/clialgo/command/RemoveCommandTest.java
  src/test/java/seedu/clialgo/command/TopoCommandTest.java
  src/test/java/seedu/clialgo/logic/TopicManagerTest.java
  src/test/java/seedu/clialgo/logic/TopicTest.java
  src/test/java/seedu/clialgo/storage/FileManagerStub.java
  src/test/java/seedu/clialgo/storage/FileManagerTest.java
Labels: type.Task, priority.Medium

#247 Add style.iuml file to standardise style in uml diagrams v2.1
  docs/class-diagrams/diagrams/AddClass.png
  docs/class-diagrams/source-files/AddClass.puml
  docs/sequence-diagrams/diagrams/AddEntry.png
  docs/sequence-diagrams/diagrams/AddFeature.png
  docs/sequence-diagrams/diagrams/Architecture.png
  docs/sequence-diagrams/source-files/AddEntry.puml
  docs/sequence-diagrams/source-files/AddFeature.puml
  docs/sequence-diagrams/source-files/Architecture.puml
  docs/style.iuml
Labels: type.Task, priority.Medium

#248 Add style to puml diagrams
  docs/class-diagrams/diagrams/AddClass.png
  docs/class-diagrams/diagrams/ExportClass.png
  docs/class-diagrams/diagrams/FileManagerClass.png
  docs/class-diagrams/source-files/AddClass.puml
  docs/class-diagrams/source-files/ExportClass.puml
  docs/class-diagrams/source-files/FileManagerClass.puml
  docs/sequence-diagrams/diagrams/AddEntry.png
  docs/sequence-diagrams/diagrams/AddFeature.png
  docs/sequence-diagrams/diagrams/Architecture.png
  docs/sequence-diagrams/diagrams/Export.png
  docs/sequence-diagrams/diagrams/InitializationFileManager.png
  docs/sequence-diagrams/source-files/AddEntry.puml
  docs/sequence-diagrams/source-files/AddFeature.puml
  docs/sequence-diagrams/source-files/Architecture.puml
  docs/sequence-diagrams/source-files/Export.puml
  docs/sequence-diagrams/source-files/InitializationFileManager.puml
  src/main/java/seedu/clialgo/storage/SingleFile.java
Labels: type.Task, priority.Medium

#257 Update documentation v2.1
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/class-diagrams/diagrams/ArchitectureDiagram.png
  docs/class-diagrams/diagrams/FilterClass.png
  docs/class-diagrams/diagrams/ListClass.png
  docs/class-diagrams/diagrams/ParserClass.png
  docs/class-diagrams/diagrams/TopicManagerClass.png
  docs/class-diagrams/source-files/ArchitectureDiagram.puml
  docs/class-diagrams/source-files/FilterClass.puml
  docs/class-diagrams/source-files/ListClass.puml
  docs/class-diagrams/source-files/ParserClass.puml
  docs/class-diagrams/source-files/TopicManagerClass.puml
  docs/sequence-diagrams/diagrams/Architecture.png
  docs/sequence-diagrams/diagrams/FilterByTopic.png
  docs/sequence-diagrams/diagrams/ListFeature.png
  docs/sequence-diagrams/diagrams/Parser.png
  docs/sequence-diagrams/diagrams/TopicManager.png
  docs/sequence-diagrams/source-files/Architecture.puml
  docs/sequence-diagrams/source-files/FilterByTopic.puml
  docs/sequence-diagrams/source-files/ListFeature.puml
  docs/sequence-diagrams/source-files/Parser.puml
  docs/sequence-diagrams/source-files/TopicManager.puml
  docs/style.iuml
  docs/team/heejet.md
  docs/team/lohjooh.md
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/CLIAlgo.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/ExportCommand.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/FilterCommand.java
  src/main/java/seedu/clialgo/command/HelpCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/main/java/seedu/clialgo/storage/FileDecoder.java
  src/main/java/seedu/clialgo/storage/FileEncoder.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/test/java/seedu/clialgo/BufferTest.java
  src/test/java/seedu/clialgo/command/AddCodeCommandTest.java
  src/test/java/seedu/clialgo/command/AddCommandTest.java
  src/test/java/seedu/clialgo/command/AddNoteCommandTest.java
  src/test/java/seedu/clialgo/command/ExitTestModeCommandTest.java
  src/test/java/seedu/clialgo/command/FilterCommandTest.java
  src/test/java/seedu/clialgo/command/HelpCommandTest.java
  src/test/java/seedu/clialgo/command/InvalidTopicCommandTest.java
  src/test/java/seedu/clialgo/command/ListCommandTest.java
  src/test/java/seedu/clialgo/command/NameNotFoundCommandTest.java
  src/test/java/seedu/clialgo/command/RemoveCommandTest.java
  src/test/java/seedu/clialgo/command/TopoCommandTest.java
  src/test/java/seedu/clialgo/storage/FileDecoderTest.java
  src/test/java/seedu/clialgo/storage/FileManagerTest.java
  src/test/java/seedu/clialgo/storage/SingleFileTest.java
Labels: type.Task, priority.Medium

#259 Add Activation Box Colours, Add Security Exception Support
  docs/class-diagrams/diagrams/ExportClass.png
  docs/class-diagrams/diagrams/FileManagerClass.png
  docs/class-diagrams/source-files/ExportClass.puml
  docs/class-diagrams/source-files/FileManagerClass.puml
  docs/sequence-diagrams/diagrams/AddEntry.png
  docs/sequence-diagrams/diagrams/Export.png
  docs/sequence-diagrams/diagrams/InitializationFileManager.png
  docs/sequence-diagrams/source-files/AddEntry.puml
  docs/sequence-diagrams/source-files/Export.puml
  docs/sequence-diagrams/source-files/InitializationFileManager.puml
  docs/style.iuml
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/main/java/seedu/clialgo/storage/SingleFile.java
Labels: type.Task, priority.Medium

#258 Branch diagrams v2.1
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/class-diagrams/diagrams/HelpCommand.png
  docs/class-diagrams/diagrams/UiClass.png
  docs/class-diagrams/source-files/HelpCommand.puml
  docs/class-diagrams/source-files/UiClass.puml
  docs/sequence-diagrams/diagrams/HelpFeature.png
  docs/sequence-diagrams/diagrams/Ui.png
  docs/sequence-diagrams/source-files/HelpFeature.puml
  docs/sequence-diagrams/source-files/Ui.puml
  docs/team/nikkiDEEE.md
Labels: type.Task, priority.Medium

#246 Add JUnit tests for FilterCommand
  src/test/java/seedu/clialgo/command/FilterByTopicCommandTest.java
  src/test/java/seedu/clialgo/command/FilterCommandTest.java
Labels: type.Task, priority.Medium

#261 Branch Add UML Diagrams Colour, Update UML Diagrams Size and Links in DG v2.1
  docs/DeveloperGuide.md
  docs/README.md
  docs/class-diagrams/diagrams/TopoCommandClass.png
  docs/class-diagrams/source-files/TopoCommandClass.puml
  docs/sequence-diagrams/diagrams/TopoSort.png
  docs/sequence-diagrams/source-files/TopoSort.puml
  docs/team/ong-ck.md
Labels: type.Task, priority.Medium

#262 Code refactoring v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/class-diagrams/diagrams/ArchitectureDiagram.png
  docs/class-diagrams/source-files/ArchitectureDiagram.puml
  docs/team/heejet.md
Labels: type.Task, priority.Medium

#264 Refactor DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/clialgo/logic/TopicManager.java
Labels: type.Task, priority.Medium

#265 Branch final edits v2.1
  docs/team/lohjooh.md
  docs/team/nicholas132000.md
  docs/team/nikkiDEEE.md
  docs/team/ong-ck.md
  src/main/java/seedu/clialgo/storage/FileDecoder.java
Labels: type.Task, priority.Medium

#267 Final Refactor of UG, DG and PPP v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ong-ck.md
Labels: type.Task, priority.Medium

#268 Branch final changes v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/clialgo/Parser.java
  src/main/java/seedu/clialgo/command/ExitCommand.java
  src/main/java/seedu/clialgo/command/HelpCommand.java
  src/main/java/seedu/clialgo/command/InvalidCommand.java
  src/main/java/seedu/clialgo/command/InvalidFilterCommand.java
  src/main/java/seedu/clialgo/command/InvalidImportanceCommand.java
  src/main/java/seedu/clialgo/command/InvalidTopicCommand.java
  src/main/java/seedu/clialgo/command/ListCommand.java
  src/main/java/seedu/clialgo/command/NameNotFoundCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/main/java/seedu/clialgo/command/TestModeCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/main/java/seedu/clialgo/exceptions/parser/EmptyFieldException.java
  src/main/java/seedu/clialgo/exceptions/parser/NullInputException.java
  src/main/java/seedu/clialgo/file/CS2040CFile.java
  src/main/java/seedu/clialgo/file/Code.java
  src/main/java/seedu/clialgo/file/Note.java
  src/main/java/seedu/clialgo/logic/Topic.java
  src/test/java/seedu/clialgo/storage/FileManagerStub.java
Labels: type.Task, priority.Medium

#269 Fix Portfolio Link in AboutUs
  docs/AboutUs.md
Labels: type.Bug, priority.Low

#270 Reformat table in AboutUs.md
  docs/AboutUs.md
Labels: type.Task, priority.Low

#271 Fix bug in TopoCommand
  src/main/java/seedu/clialgo/command/TopoCommand.java
Labels: priority.High, severity.Low
