Repository AY2223S2-CS2113-T15-1/tp, pull requests merged in 2023-03, with the labels that each got.

#56 Ui JUnit test v1.0b
  src/main/java/seedu/clialgo/Ui.java
  src/test/java/seedu/clialgo/UiTest.java
Labels: type.Task, priority.High

#65 TopicManager JUnit test v1.0b
  src/test/java/seedu/clialgo/TopicManagerTest.java
  src/test/java/seedu/clialgo/TopicTest.java
Labels: type.Task, priority.High

#68 RemoveCommand JUnit v1.0b
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/test/java/seedu/clialgo/command/AddCommandTest.java
  src/test/java/seedu/clialgo/command/RemoveCommandTest.java
Labels: type.Task, priority.High

#69 Parser JUnit test v1.0b
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/FilterCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/test/java/seedu/clialgo/ParserTest.java
  src/test/java/seedu/clialgo/UiTest.java
  src/test/java/seedu/clialgo/command/AddCommandTest.java
  src/test/java/seedu/clialgo/command/FilterCommandTest.java
  src/test/java/seedu/clialgo/command/RemoveCommandTest.java
Labels: type.Task, priority.High

#70 Add JUnit test for RemoveCommand class
  src/test/java/seedu/clialgo/command/RemoveCommandTest.java
Labels: type.Task, priority.High

#86 Add template classes for v2.0
  src/main/java/seedu/clialgo/Topic.java
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/command/AddCodeCommand.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/AddNoteCommand.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/PipelineCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/main/java/seedu/clialgo/file/Code.java
  src/main/java/seedu/clialgo/file/File.java
  src/main/java/seedu/clialgo/file/Note.java
  src/main/java/seedu/clialgo/storage/FileDecoder.java
  src/main/java/seedu/clialgo/storage/FileEncoder.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/main/java/seedu/clialgo/storage/SingleFile.java
  src/test/java/seedu/clialgo/TopicManagerTest.java
  src/test/java/seedu/clialgo/TopicTest.java
  src/test/java/seedu/clialgo/command/ListCommandTest.java
Labels: type.Task, priority.Medium

#95 Manual testing in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#88 Branch check file exist v2.0
  src/main/java/seedu/clialgo/FileType.java
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/test/java/seedu/clialgo/UiTest.java
  src/test/java/seedu/clialgo/command/AddCommandTest.java
  src/test/java/seedu/clialgo/command/RemoveCommandTest.java
Labels: type.Enhancement, priority.Medium

#98 Update user stories in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#97 Branch topic linkages v2.0
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/ExitTestModeCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
Labels: type.Bug, type.Story, priority.High, severity.VeryLow

#107 Add Design for Add, NFR in developer guide and update code files support
  docs/DeveloperGuide.md
  docs/UML/diagrams/Add.png
  docs/UML/source-files/Add.puml
  src/main/java/seedu/clialgo/Parser.java
  src/main/java/seedu/clialgo/Topic.java
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/AddCodeCommand.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/AddNoteCommand.java
  src/main/java/seedu/clialgo/command/Command.java
  src/main/java/seedu/clialgo/command/ExitCommand.java
  src/main/java/seedu/clialgo/command/ExitTestModeCommand.java
  src/main/java/seedu/clialgo/command/FilterCommand.java
  src/main/java/seedu/clialgo/command/InvalidTopicCommand.java
  src/main/java/seedu/clialgo/command/ListCommand.java
  src/main/java/seedu/clialgo/command/NameNotFoundCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/main/java/seedu/clialgo/command/TestModeCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/main/java/seedu/clialgo/file/CS2040CFile.java
  src/main/java/seedu/clialgo/file/Code.java
  src/main/java/seedu/clialgo/file/File.java
  src/main/java/seedu/clialgo/file/Note.java
  src/main/java/seedu/clialgo/storage/FileDecoder.java
  src/main/java/seedu/clialgo/storage/FileEncoder.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/main/java/seedu/clialgo/storage/SingleFile.java
  src/test/java/seedu/clialgo/TopicManagerTest.java
  src/test/java/seedu/clialgo/TopicTest.java
  src/test/java/seedu/clialgo/UiTest.java
  src/test/java/seedu/clialgo/command/AddCommandTest.java
  src/test/java/seedu/clialgo/command/HelpCommandTest.java
  src/test/java/seedu/clialgo/command/ListCommandTest.java
  src/test/java/seedu/clialgo/command/NameNotFoundCommandTest.java
  src/test/java/seedu/clialgo/command/RemoveCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, type.Story, priority.High

#110 Branch UML for TopoCommand v2.0
  docs/DeveloperGuide.md
  docs/uml/diagrams/TopoCommandClass.png
  docs/uml/source-files/TopoCommandClass.puml
Labels: type.Task, priority.High

#111 Add Ui Class Diagram
  docs/uml/diagrams/UiClass.png
  docs/uml/source-files/UiClass.puml
Labels: type.Task, priority.High

#126 Fix buffer message bug
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/storage/FileDecoder.java
Labels: severity.Medium

#115 Add inheritance to FilterCommand
  src/main/java/seedu/clialgo/Parser.java
  src/main/java/seedu/clialgo/StringManipulation.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/AddCodeCommand.java
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/AddNoteCommand.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/FilterCommand.java
  src/main/java/seedu/clialgo/command/InvalidImportanceCommand.java
  src/main/java/seedu/clialgo/exceptions/parser/NullInputException.java
  src/main/java/seedu/clialgo/exceptions/parser/NumberFormatException.java
  src/main/java/seedu/clialgo/file/CS2040CFile.java
  src/main/java/seedu/clialgo/file/Note.java
  src/main/java/seedu/clialgo/storage/FileManager.java
Labels: type.Story, priority.High

#128 Branch filter support buffer v2.0
  docs/UserGuide.md
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/CLIAlgo.java
  src/main/java/seedu/clialgo/Parser.java
  src/main/java/seedu/clialgo/StringManipulation.java
  src/main/java/seedu/clialgo/Topic.java
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/EmptyBufferCommand.java
  src/main/java/seedu/clialgo/command/ExportCommand.java
  src/main/java/seedu/clialgo/command/FilterByImportanceCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/FilterCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/main/java/seedu/clialgo/exceptions/parser/NumberFormatException.java
  src/main/java/seedu/clialgo/storage/FileManager.java
  src/main/java/seedu/clialgo/storage/SingleFile.java
  src/test/java/seedu/clialgo/ParserTest.java
  src/test/java/seedu/clialgo/TopicManagerTest.java
  src/test/java/seedu/clialgo/TopicTest.java
  src/test/java/seedu/clialgo/command/FilterCommandTest.java
  src/test/java/seedu/clialgo/command/ListCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, type.Task, type.Story, type.Enhancement, priority.High, severity.Medium

#130 Update DG with sequence diagram
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/export1.png
  docs/images/export2.png
  docs/sequence/diagrams/Export.png
  docs/sequence/diagrams/InitializationFileManager.png
  docs/sequence/source-files/Export.puml
  docs/sequence/source-files/InitializationFileManager.puml
  docs/uml/diagrams/FileManagerClass.png
  docs/uml/source-files/FileManagerClass.puml
  src/main/java/seedu/clialgo/Buffer.java
  src/main/java/seedu/clialgo/Ui.java
Labels: type.Task, priority.High

#132 UG Intro, Quick Start and Help feature
  docs/UserGuide.md
  src/main/java/seedu/clialgo/Parser.java
Labels: type.Task, priority.High

#137 Branch add sequence diagram to DG and update UG v2.0
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/sequence/diagrams/TopoSort.png
  docs/sequence/source-files/TopoSort.puml
  src/main/java/seedu/clialgo/command/TopoCommand.java
Labels: type.Task, priority.High

#134 Update developer guide and user guide and sequence diagram and some j…
  docs/DeveloperGuide.md
  docs/UML/diagrams/Add.png
  docs/UML/source-files/Add.puml
  docs/UserGuide.md
  docs/sequence/diagrams/AddFeature.png
  docs/sequence/source-files/AddFeature.puml
  src/main/java/seedu/clialgo/command/AddCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/test/java/seedu/clialgo/TopicManagerTest.java
  src/test/java/seedu/clialgo/TopicTest.java
  src/test/java/seedu/clialgo/command/AddCommandTest.java
Labels: type.Task, priority.High

#139 Add filter implementation v2.0
  docs/DeveloperGuide.md
  docs/UML/diagrams/Add.png
  docs/UML/diagrams/ArchitectureDiagram.png
  docs/UML/diagrams/FilterClass.png
  docs/UML/diagrams/HelpCommand.png
  docs/UML/diagrams/ParserClass.png
  docs/UML/source-files/Add.puml
  docs/UML/source-files/ArchitectureDiagram.puml
  docs/UML/source-files/FilterClass.puml
  docs/UML/source-files/HelpCommand.puml
  docs/UserGuide.md
  docs/sequence/diagrams/Architecture.png
  docs/sequence/diagrams/FilterByTopic.png
  docs/sequence/diagrams/Parser.png
  docs/sequence/source-files/Architecture.puml
  docs/sequence/source-files/FilterByTopic.puml
  docs/sequence/source-files/Parser.puml
  docs/uml/diagrams/ParserClass.png
  docs/uml/diagrams/TopoCommandClass.png
  docs/uml/diagrams/UiClass.png
  docs/uml/source-files/ParserClass.puml
  docs/uml/source-files/TopoCommandClass.puml
  docs/uml/source-files/UiClass.puml
  src/main/java/seedu/clialgo/Parser.java
  src/main/java/seedu/clialgo/Topic.java
  src/main/java/seedu/clialgo/TopicManager.java
  src/main/java/seedu/clialgo/Ui.java
  src/main/java/seedu/clialgo/command/ExportCommand.java
  src/main/java/seedu/clialgo/command/FilterByTopicCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/test/java/seedu/clialgo/TopicManagerTest.java
  src/test/java/seedu/clialgo/TopicTest.java
Labels: type.Bug, type.Task, type.Enhancement, priority.High, severity.High

#140 Update parser unit v2.0b
  docs/DeveloperGuide.md
  docs/sequence/diagrams/Parser.png
  docs/sequence/source-files/Parser.puml
  src/main/java/seedu/clialgo/Parser.java
  src/main/java/seedu/clialgo/command/ExitTestModeCommand.java
  src/main/java/seedu/clialgo/command/RemoveCommand.java
  src/main/java/seedu/clialgo/command/TestModeCommand.java
  src/main/java/seedu/clialgo/command/TopoCommand.java
  src/test/java/seedu/clialgo/ParserTest.java
  src/test/java/seedu/clialgo/StringManipulationTest.java
  src/test/java/seedu/clialgo/command/NameNotFoundCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#151 Update instructions for Add feature to be clearer
  docs/UserGuide.md
Labels: type.Task
